### ISSUE TITLE
Added a config option to reduce the number of full_node worker processes to reduce ram usage

### ISSUE THREAD

**Issue by grayfallstown** [Tad-Network/tad-blockchain#12]
There is a bug on github that prevents me from creating an actual pull request to your fork: https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github

Can you please merge this code change?
https://github.com/pinksheetscrypto/covid-blockchain/pull/21

**Comment by TheTad** [comment]
Thanks, it is very useful. Will do the next release!

**Comment by TheTad** [comment]
@grayfallstown hey this has been merged to the `main` branch. Again, thanks for the suggestion!
