### ISSUE TITLE
[BUG]Not Found Plots

### ISSUE THREAD

**Issue by ntluojianlin** [Tad-Network/tad-blockchain#9]
Not Found Plots？

**Comment by fabitom** [comment]
import plot keys before.

**Comment by TheTad** [comment]
Very likely @fabitom is right
If plots are not found it's most likely problem with wrong key.
Try to remove `.tad` from the home folder and start it over

@ntluojianlin Please let is know if that helped

**Comment by TheTad** [comment]
No updates on the issue since then, closing it down
